site_name: Astraeus-I
repo_url: https://github.com/Astraeus-I
repo_name: Astraeus-I

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/small.ico
  font:
    text: Montserrat
  features:
    - navigation.tabs
    - content.tabs.link
    - toc.integrate
    - navigation.tracking
    - navigation.footer
    - content.code.annotation
    - content.code.copy
    - search.suggest
    - navigation.top
    # - navigation.expand
  highlightjs: true
  hljs_style:
    - monokai
  language: en
  palette:
    - scheme: preference
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: indigo
      accent: deep purple
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
      primary: indigo
      accent: deep purple

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - 'stylesheets/extra.js'

nav:
    - 'ğŸ¡ Home': 'index.md'
    - 'ğŸš€ Getting Started': 'getting_started/getting_started.md'
    - 'ğŸ“– User Guide': 'user_guide/user_guide.md'
    - 'ğŸ“š API': 'api/api.md'
    - 'ğŸ“Š About': 'about/about.md'
    - 'ğŸ“‹ Order Form': 'order_form/order_form.md'

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Astraeus-I
    - icon: fontawesome/brands/discord
      link: https://discord.gg/7H8FzkXEgZ

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2023 <a href="https://github.com/Astraeus-I"  target="_blank" rel="noopener">Astraeus-I</a>